import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-screen flex'>
        <main className='flex flex-col mx-auto px-14 mt-28 gap-2 font-montserrat container items-center lg:items-start'>
          <h1 className='font-bold text-6xl text-white_1 font-rowdies md:text-9xl'>
            MEMO<span className='text-red_1'>PRO</span>
          </h1>
          <h2 className='font-bold text-3xl max-w-3xl text-white_1 uppercase text-center lg:text-left md:text-5xl'>
            Effortlessly jot down and keep track of your notes, ideas, and to-dos with MEMO<span className='text-red_1'>PRO</span>
          </h2>
          <div className='flex flex-col gap-4 mt-5 text-white_1 md:flex-row'>
            <button className='p-4 rounded-xl font-medium text-2xl bg-light_blue_1 w-60 duration-150 transition ease-in-out hover:bg-white_1 hover:text-red_1'>
              REGISTER
            </button>
            <button className='p-4 rounded-xl font-medium text-2xl bg-light_blue_1 w-60 duration-150 transition ease-in-out hover:bg-white_1 hover:text-red_1'>
              LOGIN
            </button>
          </div>
        </main>
      </div>
    </>
  )
}
